# Generated by Django 5.2.6 on 2025-11-14 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id_colaborador', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('contato', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'colaborador',
            },
        ),
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('id_comunidade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'comunidade',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('colaborador', 'Colaborador'), ('voluntario', 'Voluntário'), ('paciente', 'Paciente')], default='paciente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='EspacoComunitario',
            fields=[
                ('id_espaco_comunitario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('id_comunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='espacos', to='core.comunidade')),
            ],
            options={
                'db_table': 'espaco_comunitario',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_comunidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.comunidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id_atendimento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('tipo_atendimento', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_espaco_comunitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='core.espacocomunitario')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.paciente')),
            ],
            options={
                'db_table': 'atendimento',
            },
        ),
        migrations.CreateModel(
            name='Acompanhamento',
            fields=[
                ('id_acompanhamento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('descricao', models.TextField(blank=True)),
                ('situacao', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamentos', to='core.paciente')),
            ],
            options={
                'db_table': 'acompanhamento',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id_voluntario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('universidade', models.CharField(blank=True, max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voluntario_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voluntario',
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id_disponibilidade', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('id_voluntario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='core.voluntario')),
            ],
            options={
                'db_table': 'disponibilidade',
            },
        ),
        migrations.CreateModel(
            name='Participar',
            fields=[
                ('id_participar', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.atendimento')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='core.paciente')),
            ],
            options={
                'db_table': 'participar',
                'unique_together': {('id_atendimento', 'id_paciente')},
            },
        ),
    ]
