# Generated by Django 5.2.6 on 2025-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voluntario',
            name='contato',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
