# Generated by Django 5.2.6 on 2025-11-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paciente_data_nascimento_voluntario_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='id_voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.voluntario'),
        ),
    ]
